import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from logger import setup_logger
from config.settings import (
    SMTP_HOST,
    SMTP_PORT,
    SENDER_MAIL,
    SENDER_MAIL_PASSWORD,
    RECEIVER_MAIL,
)

logger = setup_logger()

MITRE_BASE = "https://cve.mitre.org/cgi-bin/cvename.cgi?name="


def format_email(advisory: dict) -> MIMEMultipart:
    """
    Creates a minimal, SOC-ready advisory email.
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"{advisory['title']}"
    msg["From"] = SENDER_MAIL
    msg["To"] = RECEIVER_MAIL

    # ---- CVE Links ----
    if advisory.get("cves") and advisory["cves"] != ["Not listed"]:
        cve_links = "<br>".join(
            f'<a href="{MITRE_BASE}{cve}">{cve}</a>' for cve in advisory["cves"]
        )
    else:
        cve_links = "No CVEs assigned"

    # ---- Affected Products ----
    affected_products = "<br>".join(
        advisory.get("affected_products", ["Not listed"])
    )

    # ---- Email Body ----
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; font-size: 13px;">
        <h3>{advisory['vendor']} Security Advisory</h3>

        <table cellpadding="6">
            <tr><td><b>Vendor</b></td><td>{advisory['vendor']}</td></tr>
            <tr><td><b>Advisory Name</b></td><td>{advisory['title']}</td></tr>
            <tr><td><b>Advisory ID</b></td><td>{advisory['advisory_id']}</td></tr>
            <tr><td><b>First Published</b></td><td>{advisory.get('first_published', 'Not available')}</td></tr>
            <tr><td><b>CVSS Score</b></td><td>{advisory.get('cvss', 'Not available')}</td></tr>
            <tr><td><b>CVSS Vector</b></td><td>{advisory.get('vector', 'Not available')}</td></tr>
            <tr><td><b>Severity</b></td><td>{advisory.get('severity', 'Not available')}</td></tr>
            <tr><td><b>CVEs</b></td><td>{cve_links}</td></tr>
        </table>

        <h4>Description</h4>
        <p>{advisory.get('description', 'No description available')}</p>

        <h4>Affected Products</h4>
        <p>{affected_products}</p>

        <hr>
        <p>
            <a href="{advisory['source_url']}">View Full Advisory</a>
        </p>

        <p style="color: #666; font-size: 11px;">
            Generated by NeoSpyder | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
        </p>
    </body>
    </html>
    """

    msg.attach(MIMEText(html_body, "html"))
    return msg


def send_email(msg: MIMEMultipart, vendor: str | None = None):
    """
    Sends email via SMTP using STARTTLS.

    Args:
        msg: Email message
        vendor: Optional vendor name for cleaner logging
    """
    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(SENDER_MAIL, SENDER_MAIL_PASSWORD)
            server.send_message(msg)

        # ---- SINGLE CLEAN SUCCESS LOG ----
        if vendor:
            logger.info(f"{vendor} advisory email sent successfully")
        else:
            logger.info("Advisory email sent successfully")

    except smtplib.SMTPAuthenticationError:
        logger.error("SMTP authentication failed — check App Password")

    except Exception as e:
        logger.error(f"Failed to send email: {e}")