name: NeoSpyder Intelligence Engine

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:

  run-neospyder:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chromium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

      - name: Run NeoSpyder
        env:
          SENDER_MAIL: ${{ secrets.SENDER_MAIL }}
          SENDER_MAIL_PASSWORD: ${{ secrets.SENDER_MAIL_PASSWORD }}
          RECEIVER_MAIL: ${{ secrets.RECEIVER_MAIL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          python main.py
